blog/urls.py
from django.urls import path, re_path, include
from blog import views

urlpatterns = [
    re_path('^$', views.blog_index, name='blog_index'),
    re_path('^article/(?P<article_id>[0-9]+)$', views.article_page, name='article_page'),
    re_path(r'^edit/(?P<article_id>[0-9]+)$', views.edit_page, name='edit_page'),
    re_path(r'^edit/action/$', views.edit_action, name='edit_action'),
    # re_path('^search/', include('haystack.urls')),
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from blog.views import homepage

urlpatterns = [
    re_path('admin/', admin.site.urls),
    re_path('^$', homepage),
    re_path('^blog/', include(('blog.urls', 'blog'), namespace='blog')),
    re_path('mdeditor/', include('mdeditor.urls')),

]

blog/models.py
from django.db import models
from mdeditor.fields import MDTextField
from django.utils import timezone


class Tags(models.Model):
    name = models.CharField('文章标签', max_length=15)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name', )
        verbose_name = "标签"
        verbose_name_plural = verbose_name


class Article(models.Model):
    title = models.CharField('文章标题', max_length=30)
    content = MDTextField('文章内容', null=True)
    pub_time = models.DateField('发布时间', null=True, default=timezone.now)
    page_views = models.BigIntegerField('阅读量', default=0)
    CAT_CHOICES = (
        ('tech', 'Tech'),
        ('design', 'Design'),
        ('life', 'Life'),
        ('tips', 'Tips'),
        ('resource', 'Resource'),
    )
    synopsis = models.TextField('文章概要', null=True, max_length=200, default=" ")
    category = models.CharField('文章类别', null=True, max_length=15, choices=CAT_CHOICES)
    tag = models.ManyToManyField(Tags, verbose_name='文章标签')
    next_id = models.IntegerField(default=0)
    prev_id = models.IntegerField(default=0)
    number = models.IntegerField(default=0)
    class Meta:
        ordering = ('title', )
        verbose_name = '博客文章'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class User(models.Model):
    name = models.CharField(null=True, blank=True, max_length=15)

    def __str__(self):
        return self.name


class Comment(models.Model):
    name = models.CharField(max_length=25, default='匿名用户')
    content = models.CharField(max_length=200)
    time = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

    class Meta:
        ordering = ('time', )
        verbose_name = '评论'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.content[:20]


class Count(models.Model):
    blog_num = models.IntegerField(default=0)
    tag_num = models.IntegerField(default=0)
    visitor_num = models.IntegerField(default=0)

    class Meta:
        verbose_name = '数量统计'
        verbose_name_plural = verbose_name

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from . import models
import markdown
from django.views.generic import View, ListView
from pure_pagination.mixins import PaginationMixin
from pure_pagination import Paginator, PageNotAnInteger


class ModelListView(PaginationMixin, ListView):
    paginate_by = 10
    object = models.Article


def homepage(request):
    return render(request, 'homepage.html')


def blog_index(request):
    all_articles = models.Article.objects.all()
    article_num = all_articles.count()
    try:
        page = request.GET.get('page', 1)
    except PageNotAnInteger:
        page = 1
    p = Paginator(all_articles, request=request, per_page=6)
    articles = p.page(page)
    return render(request, 'blog_index.html', {
        'articles': articles,
        'article_num': article_num,
    })


def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    article.content = markdown.markdown(article.content,
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])
    article.next_id = str(int(article_id) + 1)
    article.prev_id = str(int(article_id) - 1)
    article.number = models.Article.objects.all().count()
    return render(request, 'article_page.html', {'article': article})


def edit_page(request, article_id):
    if article_id == '0':
        return render(request, 'edit_page.html')
    else:
        article = models.Article.objects.get(pk=article_id)
        return render(request, 'edit_page.html', {'article': article})


def edit_action(request):
    title = request.POST.get('title', 'TITLE')
    content = request.POST.get('content', 'CONTENT')
    article_id = request.POST.get('article_id', 0)
    if article_id == '0':
        models.Article.objects.create(title=title, content=content)
        articles = models.Article.objects.all()
        return render(request, 'blog_index.html', {'articles': articles})
    else:
        article = models.Article.objects.get(pk=article_id)
        article.title = title
        article.content = content
        article.save()
        return render(request, 'article_page.html', {'article': article})

templates/article_page.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}
    {{ article.title }}
{% endblock %}

<link rel="stylesheet" href="{% static 'css/semantic-ui.css' %}">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
{% block content %}
    <div class="main">
        <div class="article">
            <div class="item">
                <div class="title">
                    <h2>{{ article.title }}</h2>
                </div>
                <label class="status">发布于:{{ article.pub_time }}</label>
                {% for tag in article.tag.all %}
                    <label class="ui mini tag label">
                        {{ tag }}
                    </label>
                    <label>&nbsp;&nbsp</label>
                {% endfor %}
                <label>&nbsp;&nbsp</label>
                <label class="ui mini label">
                    &nbsp;&nbsp;&nbsp;&nbsp;{{ article.category }}&nbsp;&nbsp;&nbsp;&nbsp;
                </label>
                <div class="content">
                    {{ article.content|safe }}
                </div>
            </div>
        </div>
    </div>

    <div class="left-button">
        {% if article.id > 1 %}
            <a href="{% url 'blog:article_page' article.prev_id %}">
                <div class="ui vertical animated button" tabindex="0">
                    <div class="visible content">上一篇</div>
                    <div class="hidden content">
                        <i class="fa fa-angle-double-left" aria-hidden="true"></i>
                    </div>
                </div>
            </a>
        {% endif %}
    </div>
    <div class="right-button">
            <a href="{% url 'blog:article_page' article.next_id %}">
                <div class="ui vertical animated button" tabindex="0">
                    <div class="visible content">下一篇</div>
                    <div class="hidden content">
                        <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    </div>
                </div>
            </a>
    </div>


{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/semantic-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'md_css/github.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>


<body>
<div class="ui huge fixed inverted menu">
    <a href="/" class='item'> 王 毅 诚 的 站 点&nbsp;&nbsp;<i class="fa fa-home fa-fw"></i></a>
    <a href="/blog/" class='item'>&nbsp;博 客&nbsp;&nbsp;<i class="fa fa-book" aria-hidden="true"></i></a>
    <a href="#" class='item'>&nbsp;资 源&nbsp;&nbsp;<i class="fa fa-folder" aria-hidden="true"></i></a>
    <a href="#" class='item'>&nbsp;其 他&nbsp;&nbsp;<i class="fa fa-cog" aria-hidden="true"></i></a>
    <div class="right menu">
        <a href="#" class='item'>关 于&nbsp&nbsp</a>
    </div>
</div>

{% block content %}
{% endblock %}
{% block footer %}
    <p>Thanks for visiting my site!</p>
{% endblock %}
</body>
</html>

templates/blog_index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Yicheng's Blog
{% endblock %}


<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/semantic-ui.css' %}">

{% block content %}

    <div class="main">
        {% for article in articles.object_list reversed %}
            <div class="article-list">
                <div class="item">
                    <div class="title">
                        <a href="{% url 'blog:article_page' article.id %}">{{ article.title }}</a>
                    </div>
                    <label class="status">发布于:{{ article.pub_time }}</label>
                    {% for tag in article.tag.all %}
                        <label class="ui mini tag label">
                            {{ tag }}
                        </label>
                        <label>&nbsp;&nbsp</label>
                    {% endfor %}
                    <label>&nbsp;&nbsp</label>
                    <label class="ui mini label">
                        &nbsp;&nbsp;&nbsp;&nbsp;{{ article.category }}&nbsp;&nbsp;&nbsp;&nbsp;
                    </label>
                    <div class="content">
                        {{ article.synopsis|truncatechars:150 }}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="my_pagination">
        <div class="ui pagination menu">
            {% if articles.has_previous %}
                <a class="item prev" href="?{{ articles.previous_page_number.querystring }}">上一页</a>
            {% else %}
                <a class="disabled item">上一页</a>
            {% endif %}

            {% for page in articles.pages %}
                {% if page %}
                    {% ifequal page articles.number %}
                        <a class="active item">{{ page }}</a>
                    {% else %}
                        <a class="item" href="?{{ page.querystring }}" class="page">{{ page }}</a>
                    {% endifequal %}
                {% else %}
                    <a class="disabled item">
                        ...
                    </a>
                {% endif %}
            {% endfor %}
            {% if articles.has_next %}
                <a class="item next" href="?{{ articles.next_page_number.querystring }}">下一页</a>
            {% else %}
                <a class="disabled item">下一页</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/edit_page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
   <div class="main">
     <div class="article-list">
        <p style="text-align: center;font-size: xx-large;">编辑文章</p>
       <div class="item">

             <form action="{% url 'blog:edit_action' %}" method="post">
                 {% csrf_token %}
                 {% if article %}
                     <input type="hidden" name="article_id" value="{{ article.id }}">
                 <label>标题
                      <span class="ui fluid input">
                            <input type="text" name="title" value="{{ article.title }}">
                      </span>
                 </label>
                 <br>
                 <div class="field">
                 <label>内容
                      <span class="ui fluid input">
                            <textarea name="content" id="" cols="200" rows="20">{{ article.content }}</textarea>
                      </span>
                 </label>
                 </div>
                  {% else %}
                     <input type="hidden" name="article_id" value = '0'>
                 <label>标题
                      <span class="ui fluid input">
                            <input type="text" name="title">
                      </span>
                 </label>
                 <br>
                 <div class="field">
                 <label>内容
                      <span class="ui fluid input">
                            <textarea name="content" id="" cols="200" rows="20"></textarea>
                      </span>
                 </label>
                 </div>
                 {% endif %}
                 <div class="block"></div>
                     <input type="submit" value="提交">
             </form>
       </div>
       </div>
         <br>
     </div>
{% endblock %}

templates/homepage.html
{% load static %}
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/semantic-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'md_css/github.css' %}">
</head>

<body style="overflow-y:hidden" >
<body>
<div class="home_menu">
    <div class="ui inverted huge top fixed borderless menu">
    <a href="/" class='item'> 王 毅 诚 的 站 点&nbsp;&nbsp;<i class="fa fa-home fa-fw"></i></a>
    <a href="/blog/" class='item'>&nbsp;博 客&nbsp;&nbsp;<i class="fa fa-book" aria-hidden="true"></i></a>
    <a href="#" class='item'>&nbsp;资 源&nbsp;&nbsp;<i class="fa fa-folder" aria-hidden="true"></i></a>
    <a href="#" class='item'>&nbsp;其 他&nbsp;&nbsp;<i class="fa fa-cog" aria-hidden="true"></i></a>
    <div class="right menu">
        <a href="#" class='item'>关 于&nbsp&nbsp&nbsp<i class="fa fa-user" aria-hidden="true"></i></a>
    </div>
    </div>
</div>
</div>



<div class="headline">
    <h1>Welcome to my site !</h1>
    <div class="home_button">
        <a class="ui huge inverted animated button" href="{% url 'blog:blog_index' %}">
            <div class="visible content"> Start </div>
            <div class="hidden content">
                <i class="fa fa-arrow-right" aria-hidden="true"></i>
            </div>
        </a>
    </div>

</div>
<div class="home_img">
    <img src="https://res.cloudinary.com/dbmkzs2ez/image/upload/v1541919207/cover.png" width="100px">
</div>
{% block content %}
{% endblock %}

</body>
</html>

templates/search/search.html
{% extends 'base.html' %}
{% load highlight %}

{% block content %}

    <div class="main">
        <form method="get" action=".">
            <table>
                {{ form.as_table }}
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" value="Search">
                    </td>
                </tr>
            </table>


            {% if query %}
                <h1>以下是搜索结果: </h1>
            {% endif %}
            <br>
            {% for result in page.object_list.all %}
                <h1>什么玩意</h1>num
                <div class="article-list">
                    <div class="item">
                        <div class="title">
                            <a href="#">{{ forloop.counter }} , {% highlight result.title with query %}</a>
                        </div>
                        <div class="content">
                            {% highlight result.synopsis with query %}
                        </div>
                    </div>
                </div>
            {% empty %}
                <div class="no-post">没有搜索到相关内容，请重新搜索</div>
            {% endfor %}
        </form>
    </div>


{% endblock %}